### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by lipnikov** [xiaoyeli/superlu#39]
The last release is 4 years old. Do you plan to a make a new release? If not, which hash on the master would you recommend us to use?

**Comment by xiaoyeli** [comment]
Just made a new release v5.2.2.

**Comment by gruenich** [comment]
@xiaoyeli Thank you so much for the release! Now people relying on stable releases can profit from the fixes and polishing which went into SuperLU.

Can I ask you to also update your homepage?
On https://portal.nersc.gov/project/sparse/superlu/
* The heading is still "SuperLU Version 5.2.1"
* The download link refers to 5.2.1 instead of the GitHub repository's release or maybe better the general releases page https://github.com/xiaoyeli/superlu/releases

The changelog on https://portal.nersc.gov/project/sparse/superlu/changes.html#slu_change
* Add the missing change log entry. I propose something along

> SuperLU 5.2.2 (October 17, 2020)
> Provide pkg-config and superluConfig.cmake
> 

* Have you ever thought about reversing the order of the changes to make them anti-chronlogical?

**Comment by xiaoyeli** [comment]
updated.
